version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=places_api
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    networks:
      - places-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: places_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d places_api"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - places-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - places-network

volumes:
  postgres_data:

networks:
  places-network:
    driver: bridge